### ISSUE TITLE
Missing dependency on `importlib-resources`

### ISSUE THREAD

**Issue by asottile** [conda-forge/pre_commit-feedstock#16]
(I don't use conda, just reporting a downstream issue)

For python<3.7, `importlib-resources` is necessary: https://github.com/pre-commit/pre-commit/issues/853

**Comment by asottile** [comment]
@nicoddemus BTW if you want, you can add @deadsnakes-issues-bot and I can help with this going forward. As much as I don't like conda lol

**Comment by asottile** [comment]
Ah right, that sends me two emails :man_facepalming:

**Comment by nicoddemus** [comment]
Oh my bad, didn't notice the extra dependency!

Will be fixed by #17. 👍 

> you can add @deadsnakes-issues-bot and I can help with this going forward.

What do you mean? Add as maintainer of the feedstock?

> As much as I don't like conda lol

😢

**Comment by asottile** [comment]
> > you can add @deadsnakes-issues-bot and I can help with this going forward.
> 
> What do you mean? Add as maintainer of the feedstock?
> 

Yep, if you want :)
