### ISSUE TITLE
rename to `pre-commit`

### ISSUE THREAD

**Issue by lewisacidic** [conda-forge/pre_commit-feedstock#35]
The package name `pre_commit` (with underscore) is different to the project name `pre-commit` (with hyphen) used on:

- GitHub (https://github.com/pre-commit/pre-commit)
- the project website (https://pre-commit.com)
- PyPI (https://pypi.org/project/pre-commit/).

This makes the conda-forge package harder to find, more likely to enter incorrectly.

I propose the package be renamed. The procedure for renaming is detailed [here](https://conda-forge.org/docs/orga/guidelines.html#renaming-packages)

**Comment by xmnlab** [comment]
+1

**Comment by nicoddemus** [comment]
Done, thanks for the pointer:

https://github.com/conda-forge/staged-recipes/pull/9143

**Comment by lewisacidic** [comment]
Great, thanks for the speedy action! Should I close the issue?

**Comment by asottile** [comment]
when ready, please update [the docs](https://github.com/pre-commit/pre-commit.github.io/blob/cd46cc5c852f25963445ed71821a7e71a1adb108/index.mako#L89) -- thanks!

**Comment by nicoddemus** [comment]
> Great, thanks for the speedy action! Should I close the issue?

Let's wait until the repository is up and ready. 😁

**Comment by nicoddemus** [comment]
New repo is up:

https://github.com/conda-forge/pre-commit-feedstock

Docs PR: https://github.com/pre-commit/pre-commit.github.io/pull/258

Thanks everyone!
